# this is the default config for hxed
# you can edit this file to change the default settings
# see -h for more information on args.

# output modes: see MAN(1) or -h
output_mode=0

# heatmap modes: adaptive | fixed | none
heatmap=none

width=16
grouping=1
show_ascii=true
show_color=true
string=false
entropie=false
toggle_header=false
skip_zero=false
reverse=false
raw=false

# custom color scheme example:
# Replace R, G, B value without whitespaces
# example: CONTROL_COLOR=255;0;0 for red

#CONTROL_COLOR=R;G;B
#NULL_BYTE_COLOR=R;G;B
#ADDR_COLOR=R;G;B
#ASCII_COLOR=R;G;B
#EXTENDED_ASCII_COLOR=R;G;B
#HEADER_COLOR=R;G;B
#MAGIC_COLOR=R;G;B
#BORDER_COLOR=R;G;B
#ANALYSIS_TEXT_COLOR=R;G;B
#ERROR_COLOR=R;G;B
#HIGHLIGHT_COLOR=R;G;B