param(
    [string]$InstallScope,
    [string]$InstallDir,
    [string]$InstallMode
)

# ============================================================
#  hxed installer — Windows (PowerShell)
#  https://github.com/jjice/hxed
#  This script is AI generated by Claude, licensed under MIT
# ============================================================

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoUrl    = 'https://github.com/jjice/hxed'
$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$RepoRoot   = Split-Path -Parent $ScriptDir
$ScriptPath = $MyInvocation.MyCommand.Path

$DownloadTimeoutSec = 120

# Track installation state for rollback
$InstalledBinary  = $null
$TempFiles        = [System.Collections.Generic.List[string]]::new()

# ── Colour / output helpers ──────────────────────────────────
function Write-Header {
    Write-Host ''
    Write-Host '================================' -ForegroundColor Cyan
    Write-Host '  hxed installer'                -ForegroundColor Cyan
    Write-Host '================================' -ForegroundColor Cyan
    Write-Host ''
}

function Write-Step  { param([string]$Msg) Write-Host "  -> $Msg" -ForegroundColor Cyan }
function Write-Ok    { param([string]$Msg) Write-Host "  [OK] $Msg" -ForegroundColor Green }
function Write-Warn  { param([string]$Msg) Write-Host "  [!!] Warning: $Msg" -ForegroundColor Yellow }
function Write-Fatal {
    param([string]$Msg)
    Write-Host ''
    Write-Host "  [X] Error: $Msg" -ForegroundColor Red
    Write-Host ''
    throw $Msg
}
function Write-Divider { Write-Host '================================' -ForegroundColor Cyan }

# ── Cleanup / rollback ────────────────────────────────────────
function Invoke-Cleanup {
    param([bool]$Failed)

    foreach ($f in $TempFiles) {
        if (Test-Path $f) {
            Remove-Item -Path $f -Force -ErrorAction SilentlyContinue
        }
    }

    if ($Failed -and $InstalledBinary -and (Test-Path $InstalledBinary)) {
        Write-Warn "Rolling back — removing partially installed binary: $InstalledBinary"
        Remove-Item -Path $InstalledBinary -Force -ErrorAction SilentlyContinue
    }
}

# ── Elevation helpers ────────────────────────────────────────
function Test-IsAdministrator {
    $identity  = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = New-Object Security.Principal.WindowsPrincipal($identity)
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Invoke-RestartElevated {
    param([string]$Scope, [string]$Dir, [string]$Mode)

    $argList = @(
        '-NoProfile'
        '-ExecutionPolicy', 'Bypass'
        '-File', "`"$ScriptPath`""
        '-InstallScope', $Scope
        '-InstallDir',   "`"$Dir`""
    )
    if (-not [string]::IsNullOrWhiteSpace($Mode)) {
        $argList += @('-InstallMode', $Mode)
    }

    Write-Step 'Administrative permissions required — restarting with elevation…'
    Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList $argList | Out-Null
    exit 0
}

function Assert-ElevationForScope {
    param([string]$Scope, [string]$Dir, [string]$Mode)
    if ($Scope -ne 'systemwide') { return }
    if (Test-IsAdministrator)     { return }
    Invoke-RestartElevated -Scope $Scope -Dir $Dir -Mode $Mode
}

function Assert-DirectoryWritable {
    param([string]$Path, [string]$Scope, [string]$Mode)

    try {
        New-Item -ItemType Directory -Path $Path -Force | Out-Null
        $probe = Join-Path $Path ".hxed-probe-$PID.tmp"
        Set-Content -Path $probe -Value 'probe' -Encoding Ascii
        Remove-Item -Path $probe -Force
    }
    catch {
        if (-not (Test-IsAdministrator)) {
            Invoke-RestartElevated -Scope $Scope -Dir $Path -Mode $Mode
        }
        Write-Fatal "Cannot write to $Path even as administrator: $_"
    }
}

# ── Prompt helpers ───────────────────────────────────────────
function Read-Value {
    param([string]$Prompt, [string]$Default)
    $v = Read-Host "  $Prompt [$Default]"
    if ([string]::IsNullOrWhiteSpace($v)) { return $Default }
    return $v
}

function Read-YesNo {
    param([string]$Prompt, [bool]$Default = $true)
    $suffix = if ($Default) { '[Y/n]' } else { '[y/N]' }
    while ($true) {
        $a = Read-Host "  $Prompt $suffix"
        if ([string]::IsNullOrWhiteSpace($a)) { return $Default }
        switch ($a.Trim().ToLowerInvariant()) {
            'y'   { return $true  }
            'yes' { return $true  }
            'n'   { return $false }
            'no'  { return $false }
        }
        Write-Warn 'Please answer y or n.'
    }
}

function Read-InstallTarget {
    while ($true) {
        Write-Host ''
        Write-Host '  Install target:' -ForegroundColor White
        Write-Host "    1) Current user only  ($env:LOCALAPPDATA\Programs\hxed)"
        Write-Host "    2) Systemwide         ($env:ProgramFiles\hxed)"
        Write-Host '    3) Custom directory'
        $c = Read-Host '  Choose 1, 2, or 3 [1]'
        if ([string]::IsNullOrWhiteSpace($c)) { $c = '1' }
        switch ($c) {
            '1' { return 'local' }
            '2' { return 'systemwide' }
            '3' { return 'custom' }
        }
        Write-Warn 'Please answer with 1, 2, or 3.'
    }
}

function Read-InstallMode {
    while ($true) {
        Write-Host ''
        Write-Host '  Installation source:' -ForegroundColor White
        Write-Host '    1) Build from source (this repository)'
        Write-Host '    2) Download latest release binary from GitHub'
        $c = Read-Host '  Choose 1 or 2 [2]'
        if ([string]::IsNullOrWhiteSpace($c)) { $c = '2' }
        switch ($c) {
            '1' { return 'build' }
            '2' { return 'release' }
        }
        Write-Warn 'Please answer with 1 or 2.'
    }
}

# ── Download ─────────────────────────────────────────────────
# Uses Invoke-WebRequest (built into PowerShell 3+, Windows 8+).
# No external tools (curl, wget) required.
function Invoke-Download {
    param([string]$Uri, [string]$OutFile)

    Write-Step "Downloading from GitHub…"
    try {
        $progressPref = $ProgressPreference
        $ProgressPreference = 'SilentlyContinue'   # avoids slow progress-bar rendering

        Invoke-WebRequest `
            -Uri             $Uri `
            -OutFile         $OutFile `
            -TimeoutSec      $DownloadTimeoutSec `
            -UseBasicParsing

        $ProgressPreference = $progressPref
    }
    catch {
        $ProgressPreference = $progressPref
        Write-Fatal "Download failed (${Uri}): $_"
    }

    if (-not (Test-Path $OutFile) -or (Get-Item $OutFile).Length -eq 0) {
        Write-Fatal "Downloaded file is empty. The release asset may not exist yet: $Uri"
    }
}

# ── System checks ─────────────────────────────────────────────
function Assert-Command {
    param([string]$Name)
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        Write-Fatal "Required command not found: $Name"
    }
}

# ── Binary installation ───────────────────────────────────────
function Resolve-BuiltBinary {
    $candidates = @(
        (Join-Path $RepoRoot 'build\bin\hxed.exe'),
        (Join-Path $RepoRoot 'build\bin\Release\hxed.exe')
    )
    foreach ($c in $candidates) {
        if (Test-Path $c) { return $c }
    }
    Write-Fatal 'Build succeeded, but no hxed.exe found in build\bin or build\bin\Release.'
}

function Install-FromBuild {
    param([string]$TargetExe)

    if (-not (Test-Path (Join-Path $RepoRoot 'CMakeLists.txt'))) {
        Write-Fatal 'Build mode requires a repository checkout (CMakeLists.txt not found).'
    }
    Assert-Command 'cmake'

    Write-Step 'Configuring Release build…'
    & cmake -S $RepoRoot -B (Join-Path $RepoRoot 'build') -DCMAKE_BUILD_TYPE=Release
    if ($LASTEXITCODE -ne 0) { Write-Fatal 'CMake configuration failed.' }

    Write-Step 'Building hxed…'
    & cmake --build (Join-Path $RepoRoot 'build') --config Release
    if ($LASTEXITCODE -ne 0) { Write-Fatal 'Build failed.' }

    Copy-Item (Resolve-BuiltBinary) $TargetExe -Force
}

function Install-FromRelease {
    param([string]$TargetExe)

    $tmp = [System.IO.Path]::GetTempFileName() + '.exe'
    $TempFiles.Add($tmp)

    $releaseUrl = "$RepoUrl/releases/latest/download/hxed-windows-x64.exe"
    Invoke-Download -Uri $releaseUrl -OutFile $tmp

    Copy-Item $tmp $TargetExe -Force
}

# ── PATH management ───────────────────────────────────────────
function Add-ToUserPath {
    param([string]$Dir)

    $current = [Environment]::GetEnvironmentVariable('Path', 'User')
    $entries = if ([string]::IsNullOrWhiteSpace($current)) { @() } else { $current -split ';' }

    if ($entries -contains $Dir) {
        Write-Ok "PATH already contains $Dir."
        return
    }
    if (-not (Read-YesNo "Add $Dir to your user PATH?" $true)) {
        Write-Step "Skipped PATH update. Add $Dir manually if needed."
        return
    }

    $newPath = if ([string]::IsNullOrWhiteSpace($current)) { $Dir } else { "$current;$Dir" }
    [Environment]::SetEnvironmentVariable('Path', $newPath, 'User')
    if (-not (($env:Path -split ';') -contains $Dir)) { $env:Path = "$env:Path;$Dir" }
    Write-Ok 'User PATH updated — open a new terminal to apply.'
}

function Add-ToSystemPath {
    param([string]$Dir)

    $current = [Environment]::GetEnvironmentVariable('Path', 'Machine')
    $entries = if ([string]::IsNullOrWhiteSpace($current)) { @() } else { $current -split ';' }

    if ($entries -contains $Dir) {
        Write-Ok "PATH already contains $Dir."
        return
    }
    if (-not (Read-YesNo "Add $Dir to the system PATH?" $true)) {
        Write-Step "Skipped PATH update. Add $Dir manually if needed."
        return
    }

    $newPath = if ([string]::IsNullOrWhiteSpace($current)) { $Dir } else { "$current;$Dir" }
    [Environment]::SetEnvironmentVariable('Path', $newPath, 'Machine')
    if (-not (($env:Path -split ';') -contains $Dir)) { $env:Path = "$env:Path;$Dir" }
    Write-Ok 'System PATH updated — open a new terminal to apply.'
}

# ── Shell completions ─────────────────────────────────────────
function Install-Completion {
    param([string]$Dir, [string]$Scope)

    $src = Join-Path $RepoRoot 'completions\hxed.ps1'
    if (-not (Test-Path $src)) {
        Write-Warn "Completion file not found: $src — skipping."
        return
    }

    $dest = Join-Path $Dir 'hxed.ps1'
    try {
        Copy-Item $src $dest -Force
    }
    catch {
        Write-Warn "Could not copy completion file to $dest: $_"
        return
    }

    $profilePath = if ($Scope -eq 'systemwide') { $PROFILE.AllUsersAllHosts } else { $PROFILE }

    $profileDir = Split-Path -Parent $profilePath
    if (-not (Test-Path $profileDir)) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }
    if (-not (Test-Path $profilePath)) {
        New-Item -ItemType File -Path $profilePath -Force | Out-Null
    }

    $line = ". `"$dest`""
    if (-not (Select-String -Path $profilePath -SimpleMatch $line -Quiet)) {
        Add-Content -Path $profilePath -Value "`n$line"
    }

    Write-Ok "PowerShell completion installed via $profilePath."
}

# ════════════════════════════════════════════════════════════
#  Main
# ════════════════════════════════════════════════════════════

$installFailed = $false
try {
    Write-Header

    $defaultDir = Join-Path $env:LOCALAPPDATA 'Programs\hxed'
    $systemDir  = Join-Path $env:ProgramFiles  'hxed'

    # 1. Scope
    if ([string]::IsNullOrWhiteSpace($InstallScope)) {
        $InstallScope = Read-InstallTarget
    }

    $resolvedDir = switch ($InstallScope) {
        'local'      { if ([string]::IsNullOrWhiteSpace($InstallDir)) { $defaultDir } else { $InstallDir } }
        'systemwide' { if ([string]::IsNullOrWhiteSpace($InstallDir)) { $systemDir  } else { $InstallDir } }
        'custom'     { if ([string]::IsNullOrWhiteSpace($InstallDir)) { Read-Value 'Install hxed into which directory?' $defaultDir } else { $InstallDir } }
        default      { Write-Fatal "Unknown install scope: $InstallScope" }
    }

    # 2. Mode
    if ([string]::IsNullOrWhiteSpace($InstallMode)) {
        $InstallMode = Read-InstallMode
    }

    Write-Host ''
    Write-Step "Install directory : $resolvedDir"
    Write-Step "Platform          : Windows x64"
    Write-Host ''

    # 3. Elevation + writability
    Assert-ElevationForScope  -Scope $InstallScope -Dir $resolvedDir -Mode $InstallMode
    Assert-DirectoryWritable  -Path  $resolvedDir  -Scope $InstallScope -Mode $InstallMode

    $targetExe = Join-Path $resolvedDir 'hxed.exe'

    # 4. Install binary
    Write-Host '  Installing hxed…' -ForegroundColor White
    if ($InstallMode -eq 'build') {
        Install-FromBuild   -TargetExe $targetExe
    } else {
        Install-FromRelease -TargetExe $targetExe
    }

    $InstalledBinary = $targetExe
    Write-Ok "Binary installed: $targetExe"

    # 5. PATH
    Write-Host ''
    if ($InstallScope -eq 'systemwide') {
        Add-ToSystemPath -Dir $resolvedDir
    } elseif ($InstallScope -eq 'local') {
        Add-ToUserPath   -Dir $resolvedDir
    } else {
        Write-Step "Custom path — add $resolvedDir to PATH manually if needed."
    }

    # 6. Completions
    Write-Host ''
    if (Read-YesNo 'Install PowerShell completion as well?' $true) {
        Install-Completion -Dir $resolvedDir -Scope $InstallScope
    }

    # 7. Done
    Write-Host ''
    Write-Divider
    Write-Ok 'hxed installed successfully!'
    Write-Step "Location : $targetExe"
    Write-Step 'Open a new terminal to use hxed.'
    Write-Divider
    Write-Host ''
}
catch {
    $installFailed = $true
    # Error already printed by Write-Fatal or by PowerShell itself
}
finally {
    Invoke-Cleanup -Failed $installFailed
    if ($installFailed) { exit 1 }
}
