#!/usr/bin/env bash

# ============================================================
#  hxed installer — Linux & macOS
#  https://github.com/jjice/hxed
#  This script is AI generated by Claude, licensed under MIT
# ============================================================

set -uo pipefail

REPO_URL="https://github.com/jjice/hxed"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

DOWNLOAD_TIMEOUT=120   # seconds for curl/wget
INSTALLED_BINARY=""    # tracks what we placed, for rollback

# ── Colour helpers ───────────────────────────────────────────
if [[ -t 1 ]]; then
    C_RESET='\033[0m'
    C_BOLD='\033[1m'
    C_GREEN='\033[0;32m'
    C_YELLOW='\033[0;33m'
    C_RED='\033[0;31m'
    C_CYAN='\033[0;36m'
else
    C_RESET=''; C_BOLD=''; C_GREEN=''; C_YELLOW=''; C_RED=''; C_CYAN=''
fi

say()  { printf "${C_BOLD}%s${C_RESET}\n" "$*"; }
info() { printf "  ${C_CYAN}→${C_RESET} %s\n" "$*"; }
ok()   { printf "  ${C_GREEN}✓${C_RESET} %s\n" "$*"; }
warn() { printf "  ${C_YELLOW}⚠${C_RESET}  Warning: %s\n" "$*" >&2; }
die()  {
    printf "\n  ${C_RED}✗${C_RESET}  ${C_BOLD}Error:${C_RESET} %s\n\n" "$*" >&2
    exit 1
}

# ── Cleanup / rollback ───────────────────────────────────────
TEMP_FILES=()

register_temp() { TEMP_FILES+=("$1"); }

cleanup() {
    local exit_code=$?

    for f in "${TEMP_FILES[@]+"${TEMP_FILES[@]}"}"; do
        [[ -e "$f" ]] && rm -f "$f"
    done

    if [[ $exit_code -ne 0 && -n "$INSTALLED_BINARY" && -f "$INSTALLED_BINARY" ]]; then
        warn "Installation failed — removing partially installed binary."
        rm -f "$INSTALLED_BINARY" 2>/dev/null || true
    fi
}

trap cleanup EXIT

# ── Elevation helper ─────────────────────────────────────────
run_with_optional_elevation() {
    if "$@" 2>/dev/null; then
        return 0
    fi

    local status=$?
    if [[ ${ALLOW_ELEVATION_ON_FAILURE:-yes} == "yes" ]] && command -v sudo >/dev/null 2>&1; then
        warn "Permission denied — retrying with sudo..."
        sudo "$@"
        return $?
    fi

    if [[ ${NEEDS_ROOT:-no} == "yes" ]]; then
        die "Administrative permissions are required for ${INSTALL_DIR:-the install directory}, but sudo is not available."
    fi

    return $status
}

# ── Path / prompt helpers ────────────────────────────────────
expand_path() {
    case "$1" in
        "~")    printf '%s\n' "$HOME" ;;
        "~/"*)  printf '%s/%s\n' "$HOME" "${1#~/}" ;;
        *)      printf '%s\n' "$1" ;;
    esac
}

prompt_with_default() {
    local prompt="$1" default_value="$2" value
    read -r -p "  $prompt [$default_value]: " value
    printf '%s\n' "${value:-$default_value}"
}

# NOTE: Uses explicit return codes; callers must NOT run under set -e.
prompt_yes_no() {
    local prompt="$1"
    local default_answer="${2:-y}"
    local suffix="[Y/n]"
    [[ "$default_answer" == "n" ]] && suffix="[y/N]"

    while true; do
        local answer
        read -r -p "  $prompt $suffix: " answer
        answer="${answer:-$default_answer}"
        case "${answer,,}" in
            y|yes) return 0 ;;
            n|no)  return 1 ;;
        esac
        warn "Please answer y or n."
    done
}

prompt_target_scope() {
    while true; do
        printf '\n'
        say "Install target:"
        printf '    1) Current user only  (%s)\n' "${HOME}/.local/bin"
        printf '    2) Systemwide         (/usr/local/bin)\n'
        printf '    3) Custom directory\n'
        local answer
        read -r -p "  Choose 1, 2, or 3 [1]: " answer
        answer="${answer:-1}"
        case "$answer" in
            1) printf 'local\n';     return ;;
            2) printf 'systemwide\n'; return ;;
            3) printf 'custom\n';    return ;;
        esac
        warn "Please answer with 1, 2, or 3."
    done
}

prompt_install_mode() {
    local allow_release="$1"

    while true; do
        printf '\n'
        if [[ "$allow_release" == "yes" ]]; then
            say "Installation source:"
            printf '    1) Build from source (this repository)\n'
            printf '    2) Download latest release binary from GitHub\n'
            local answer
            read -r -p "  Choose 1 or 2 [2]: " answer
            answer="${answer:-2}"
            case "$answer" in
                1) printf 'build\n';   return ;;
                2) printf 'release\n'; return ;;
            esac
        else
            warn "No prebuilt release asset is available for this platform (${UNAME_S}/${UNAME_M})."
            local answer
            read -r -p "  Build from source instead? [Y/n]: " answer
            answer="${answer:-y}"
            case "${answer,,}" in
                y|yes) printf 'build\n'; return ;;
                n|no)  die "Installation cancelled by user." ;;
            esac
        fi
        warn "Please answer with a valid choice."
    done
}

# ── System checks ────────────────────────────────────────────
require_cmd() {
    command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

# ── Download ─────────────────────────────────────────────────
download_file() {
    local url="$1" target="$2"

    if command -v curl >/dev/null 2>&1; then
        info "Downloading with curl…"
        curl --fail --location --connect-timeout 15 --max-time "${DOWNLOAD_TIMEOUT}" \
             --retry 3 --retry-delay 2 \
             --progress-bar \
             "$url" -o "$target" \
        || die "Download failed: ${url}"
        return
    fi

    if command -v wget >/dev/null 2>&1; then
        info "Downloading with wget…"
        wget --timeout="${DOWNLOAD_TIMEOUT}" --tries=3 --waitretry=2 \
             -O "$target" "$url" \
        || die "Download failed: ${url}"
        return
    fi

    die "Neither curl nor wget is available. Please install one and re-run the installer."
}

# ── Directory helpers ────────────────────────────────────────
append_if_missing() {
    local file="$1" line="$2"
    mkdir -p "$(dirname "$file")"
    touch "$file"
    if ! grep -Fqx "$line" "$file"; then
        printf '\n%s\n' "$line" >> "$file"
    fi
}

ensure_dir() {
    run_with_optional_elevation mkdir -p "$1" \
        || die "Could not create directory: $1"
}

# ── Binary installation ──────────────────────────────────────
install_binary_from_build() {
    require_cmd cmake

    [[ -f "${REPO_ROOT}/CMakeLists.txt" ]] \
        || die "Build mode requires a repository checkout (CMakeLists.txt not found in ${REPO_ROOT})."

    info "Configuring Release build…"
    cmake -S "$REPO_ROOT" -B "${REPO_ROOT}/build" -DCMAKE_BUILD_TYPE=Release \
        || die "CMake configuration failed."

    info "Building hxed…"
    cmake --build "${REPO_ROOT}/build" --config Release \
        || die "Build failed."

    local src=""
    if   [[ -x "${REPO_ROOT}/build/bin/hxed" ]];         then src="${REPO_ROOT}/build/bin/hxed"
    elif [[ -x "${REPO_ROOT}/build/bin/Release/hxed" ]]; then src="${REPO_ROOT}/build/bin/Release/hxed"
    else die "Build succeeded, but hxed binary not found in build/bin."; fi

    run_with_optional_elevation install -m 0755 "$src" "${INSTALL_DIR}/hxed" \
        || die "Failed to install binary to ${INSTALL_DIR}/hxed."

    INSTALLED_BINARY="${INSTALL_DIR}/hxed"
}

install_binary_from_release() {
    local temp_file
    temp_file="$(mktemp)" || die "Could not create temporary file."
    register_temp "$temp_file"

    download_file "${RELEASE_URL}" "$temp_file"

    # Sanity check: ensure we actually got an executable
    if [[ ! -s "$temp_file" ]]; then
        die "Downloaded file is empty. The release asset may not exist yet: ${RELEASE_URL}"
    fi

    run_with_optional_elevation install -m 0755 "$temp_file" "${INSTALL_DIR}/hxed" \
        || die "Failed to install binary to ${INSTALL_DIR}/hxed."

    INSTALLED_BINARY="${INSTALL_DIR}/hxed"
}

# ── Shell completions ────────────────────────────────────────
install_completions() {
    local completion_root="${REPO_ROOT}/completions"
    [[ -d "$completion_root" ]] \
        || die "Completion files not found in ${completion_root}."

    local bash_src="${completion_root}/hxed.bash"
    local zsh_src="${completion_root}/_hxed"
    local fish_src="${completion_root}/hxed.fish"

    for f in "$bash_src" "$zsh_src" "$fish_src"; do
        [[ -f "$f" ]] || die "Missing completion file: $f"
    done

    if [[ "${INSTALL_SCOPE}" == "systemwide" ]]; then
        local bash_t="/usr/share/bash-completion/completions/hxed"
        local zsh_t="/usr/local/share/zsh/site-functions/_hxed"
        local fish_t="/usr/share/fish/vendor_completions.d/hxed.fish"

        run_with_optional_elevation mkdir -p "$(dirname "$bash_t")" "$(dirname "$zsh_t")" "$(dirname "$fish_t")"
        run_with_optional_elevation install -m 0644 "$bash_src" "$bash_t" || warn "Could not install Bash completion."
        run_with_optional_elevation install -m 0644 "$zsh_src"  "$zsh_t"  || warn "Could not install Zsh completion."
        run_with_optional_elevation install -m 0644 "$fish_src" "$fish_t" || warn "Could not install Fish completion."

        ok "Bash, Zsh, and Fish completions installed systemwide."
        return
    fi

    local bash_t="${HOME}/.local/share/bash-completion/completions/hxed"
    local zsh_t="${HOME}/.zsh/completions/_hxed"
    local fish_t="${HOME}/.config/fish/completions/hxed.fish"

    mkdir -p "$(dirname "$bash_t")" "$(dirname "$zsh_t")" "$(dirname "$fish_t")"
    install -m 0644 "$bash_src" "$bash_t" || warn "Could not install Bash completion."
    install -m 0644 "$zsh_src"  "$zsh_t"  || warn "Could not install Zsh completion."
    install -m 0644 "$fish_src" "$fish_t" || warn "Could not install Fish completion."

    append_if_missing "${HOME}/.zshrc" 'fpath=(~/.zsh/completions $fpath)'
    append_if_missing "${HOME}/.zshrc" 'autoload -Uz compinit && compinit'

    ok "Bash, Zsh, and Fish completions installed for current user."
}

# ── PATH management ──────────────────────────────────────────
ensure_path_entry() {
    if [[ "${INSTALL_SCOPE}" == "custom" ]]; then
        info "Custom path selected. Add ${INSTALL_DIR} to your PATH manually if needed."
        return
    fi

    if [[ ":$PATH:" == *":${INSTALL_DIR}:"* ]]; then
        ok "PATH already contains ${INSTALL_DIR}."
        return
    fi

    if ! prompt_yes_no "Add ${INSTALL_DIR} to your PATH?"; then
        info "Skipped PATH update. Add ${INSTALL_DIR} manually if needed."
        return
    fi

    if [[ "${INSTALL_SCOPE}" == "systemwide" ]]; then
        local path_file="/etc/profile.d/hxed.sh"
        local tmp_file
        tmp_file="$(mktemp)" || die "Could not create temporary file."
        register_temp "$tmp_file"
        printf 'export PATH="%s:$PATH"\n' "${INSTALL_DIR}" > "$tmp_file"
        run_with_optional_elevation install -m 0644 "$tmp_file" "$path_file" \
            || warn "Could not write ${path_file}. Add ${INSTALL_DIR} to PATH manually."
        export PATH="${INSTALL_DIR}:$PATH"
        ok "PATH updated systemwide via ${path_file}."
        return
    fi

    local shell_name
    shell_name="$(basename "${SHELL:-}")"
    local export_line="export PATH=\"${INSTALL_DIR}:\$PATH\""

    case "$shell_name" in
        bash)
            append_if_missing "${HOME}/.bashrc"  "$export_line"
            append_if_missing "${HOME}/.profile"  "$export_line"
            ;;
        zsh)
            append_if_missing "${HOME}/.zshrc"   "$export_line"
            append_if_missing "${HOME}/.profile"  "$export_line"
            ;;
        fish)
            append_if_missing "${HOME}/.config/fish/config.fish" \
                "fish_add_path \"${INSTALL_DIR}\""
            ;;
        *)
            append_if_missing "${HOME}/.profile"  "$export_line"
            ;;
    esac

    export PATH="${INSTALL_DIR}:$PATH"
    ok "PATH updated for future shells."
}

# ════════════════════════════════════════════════════════════
#  Main
# ════════════════════════════════════════════════════════════

printf '\n'
say "════════════════════════════════"
say "  hxed installer"
say "════════════════════════════════"
printf '\n'

UNAME_S="$(uname -s)"
UNAME_M="$(uname -m)"
ALLOW_RELEASE="yes"
RELEASE_ASSET=""

case "$UNAME_S" in
    Linux)
        [[ "$UNAME_M" == "x86_64" ]] && RELEASE_ASSET="hxed-linux-x64" || ALLOW_RELEASE="no"
        ;;
    Darwin)
        [[ "$UNAME_M" == "arm64" ]] && RELEASE_ASSET="hxed-macos-arm64" || ALLOW_RELEASE="no"
        ;;
    *)
        die "This installer supports Linux and macOS only. Detected: ${UNAME_S}"
        ;;
esac

DEFAULT_INSTALL_DIR="${HOME}/.local/bin"
SYSTEM_INSTALL_DIR="/usr/local/bin"
INSTALL_SCOPE="$(prompt_target_scope)"

case "$INSTALL_SCOPE" in
    local)      INSTALL_DIR="$DEFAULT_INSTALL_DIR" ;;
    systemwide) INSTALL_DIR="$SYSTEM_INSTALL_DIR" ;;
    custom)
        INSTALL_DIR="$(expand_path "$(prompt_with_default "Install hxed into which directory?" "$DEFAULT_INSTALL_DIR")")"
        ;;
esac

NEEDS_ROOT="no"
[[ "$INSTALL_SCOPE" == "systemwide" ]] && NEEDS_ROOT="yes"

printf '\n'
info "Install directory : ${INSTALL_DIR}"
info "Platform          : ${UNAME_S}/${UNAME_M}"
printf '\n'

ensure_dir "$INSTALL_DIR"

INSTALL_MODE="$(prompt_install_mode "$ALLOW_RELEASE")"
RELEASE_URL="${REPO_URL}/releases/latest/download/${RELEASE_ASSET}"

printf '\n'
say "Installing hxed…"

if [[ "$INSTALL_MODE" == "build" ]]; then
    install_binary_from_build
else
    install_binary_from_release
fi

ok "Binary installed: ${INSTALL_DIR}/hxed"

printf '\n'
ensure_path_entry

printf '\n'
if prompt_yes_no "Install shell completions as well?"; then
    install_completions
fi

printf '\n'
say "════════════════════════════════"
ok "hxed installed successfully!"
info "Location : ${INSTALL_DIR}/hxed"
info "Restart your shell or run:  source ~/.bashrc  (or equivalent)"
say "════════════════════════════════"
printf '\n'
