# fish completion for hxed

complete -c hxed -s f -l file -r -d 'Input file'
complete -c hxed -s m -l mode -r -f -a '0 1 2 3 hex bin oct dec' -d 'Output mode'
complete -c hxed -o hm -l heatmap -r -f -a 'adaptiv fixed none' -d 'Heatmap mode'
complete -c hxed -s w -l width -r -d 'Bytes per line (0 only with --raw)'
complete -c hxed -s g -l grouping -r -d 'Grouping size'
complete -c hxed -s a -l ascii -d 'Toggle ASCII column'
complete -c hxed -s c -l color -d 'Toggle color output'
complete -c hxed -s s -l string -d 'Toggle string highlighting'
complete -c hxed -s e -l entropy -d 'Toggle entropy graph'
complete -c hxed -o th -l toggle-header -d 'Toggle header/footer and magic-byte detection'
complete -c hxed -o sz -l skip-zero -d 'Toggle skip-zero lines'
complete -c hxed -o re -l reverse -d 'Toggle reverse mode'
complete -c hxed -s o -l offset -r -d 'Start offset (supports k/M/G)'
complete -c hxed -s l -l limit -r -d 'Stop at byte position (supports k/M/G)'
complete -c hxed -s r -l read-size -r -d 'Read at most N bytes (supports k/M/G)'
complete -c hxed -o se -l search -r -f -a 'a: x: d: b:' -d 'Search pattern'
complete -c hxed -s p -l pager -d 'Toggle pager output'
complete -c hxed -o ro -l raw -d 'Raw output mode'
complete -c hxed -l show-config -d 'Show current config and exit'
complete -c hxed -s h -l help -d 'Show help'
complete -c hxed -s v -l version -d 'Show version'
