#ifndef VERSION_H
#define VERSION_H

#define HXD_VERSION_MAJOR @PROJECT_VERSION_MAJOR@
#define HXD_VERSION_MINOR @PROJECT_VERSION_MINOR@
#define HXD_VERSION_PATCH @PROJECT_VERSION_PATCH@
#define HXD_VERSION "@PROJECT_VERSION@"

#endif