name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Run Basic Test
      shell: bash
      run: |
        ./build/hxd --help || echo "Help command failed"